(ns aguafria.zig.prepare
  "Prepare ordinary Clojure namespace entry points from Zig API catalogs.

  The catalog remains the authority; these small, ignored source files only
  make its namespaces discoverable by Clojure's normal loader and editors."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str])
  (:import [java.io PushbackReader]
           [java.nio.file Files Path]
           [java.security MessageDigest]
           [java.util HexFormat]))

(def ^:private generator "aguafria.zig.prepare")

(defn- read-edn [source]
  (with-open [reader (PushbackReader. (io/reader source))]
    (edn/read reader)))

(defn- digest [text]
  (.formatHex (HexFormat/of)
              (.digest (MessageDigest/getInstance "SHA-256")
                       (.getBytes ^String text "UTF-8"))))

(defn- safe-path!
  "Refuse symlinks anywhere in an output path, including its ancestors."
  [^Path path]
  (loop [part path]
    (when part
      (when (Files/isSymbolicLink part)
        (throw (ex-info "Refusing a symlink in generated output" {:path (str part)})))
      (recur (.getParent part))))
  path)

(defn- entrypoint [kind {:keys [name members]}]
  (let [namespace-name name
        [prefix loader] (case kind
                          :std ["aguafria.std." 'aguafria.zig.std/install!]
                          :packages ["aguafria.pkg." 'aguafria.zig.package/install-namespace!])
        text (str namespace-name)]
    (when-not (and (symbol? namespace-name)
                   (str/starts-with? text prefix)
                   (re-matches #"[A-Za-z_][A-Za-z0-9_-]*(\.[A-Za-z_][A-Za-z0-9_-]*)+" text))
      (throw (ex-info "Invalid catalog namespace" {:kind kind :namespace namespace-name})))
    [(str (-> text (str/replace "." "/") (str/replace "-" "_")) ".clj")
     (str ";; Generated by " generator ". Do not edit.\n"
          "(ns " namespace-name "\n"
          "  (:refer-clojure :only [])\n"
          "  (:require [" (namespace loader) "]))\n\n"
          (when (= kind :std)
            (apply str
                   (for [{:keys [clojure-name signature documentation parameters]} members]
                     (str "(clojure.core/declare ^"
                          (pr-str
                           (cond-> {:aguafria/std true
                                    :doc (str signature "\n\n" documentation)}
                             (and (seq parameters) (every? :name parameters))
                             (assoc :arglists
                                    (list 'quote (list (mapv (comp symbol :name) parameters))))))
                          " " clojure-name ")\n"))))
          "\n(" loader " clojure.core/*ns*)\n")]))

(defn write-entrypoints!
  "Refresh one catalog's entry points in `generated-dir` (default `generated`).

  Only manifest-owned, unchanged generated files may be replaced or removed.
  Unrelated files and edited generated files are preserved. Removed package
  namespaces disappear on the next prep run; restart the REPL after prep to
  discard already-loaded namespaces. Returns paths and counts, not the catalog."
  [{:keys [kind namespaces generated-dir]
    :or {generated-dir "generated"}}]
  (when-not (and (#{:std :packages} kind)
                 (string? generated-dir)
                 (not (str/blank? generated-dir)))
    (throw (ex-info "Expected a catalog kind and generated directory"
                    {:kind kind :generated-dir generated-dir})))
  (locking #'write-entrypoints!
    (let [root (safe-path! (.normalize (.toAbsolutePath (.toPath (io/file generated-dir)))))
          manifest-path (.resolve root (str ".aguafria-" (name kind) "-entrypoints.edn"))
          _ (safe-path! manifest-path)
          manifest (when (.exists (.toFile manifest-path)) (read-edn (.toFile manifest-path)))
          _ (when (and manifest
                       (not (and (= generator (:generator manifest))
                                 (= kind (:kind manifest))
                                 (map? (:files manifest)))))
              (throw (ex-info "Unrecognized generated manifest" {:path (str manifest-path)})))
          entries (mapv #(entrypoint kind %)
                        (remove #(= 'aguafria.std (:name %)) namespaces))
          sources (into (sorted-map) entries)
          _ (when-not (= (count entries) (count sources))
              (throw (ex-info "Catalog namespaces have colliding resource paths" {:kind kind})))
          previous (:files manifest)
          all-paths (sort (into (set (keys sources)) (keys previous)))
          stale (remove #(contains? sources %) (keys previous))]
      ;; Validate the complete write/delete set before changing any file.
      (doseq [relative all-paths]
        (when-not (and (string? relative)
                       (re-matches #"aguafria/(std|pkg)/[A-Za-z0-9_/]+\.clj" relative)
                       (str/starts-with? relative (if (= kind :std) "aguafria/std/" "aguafria/pkg/")))
          (throw (ex-info "Unsafe generated manifest path" {:path relative})))
        (let [path (safe-path! (.resolve root ^String relative))
              file (.toFile path)]
          (when (.exists file)
            (when-not (and (.isFile file)
                           (if-let [expected (get previous relative)]
                             (= expected (digest (slurp file)))
                             (= (get sources relative) (slurp file))))
              (throw (ex-info "Refusing to overwrite or remove an edited/non-generated file"
                              {:path (str path)}))))))
      (doseq [[relative source] sources]
        (let [file (.toFile (.resolve root ^String relative))]
          (when-not (and (.isFile file) (= source (slurp file)))
            (io/make-parents file)
            (spit file source))))
      (doseq [relative stale]
        (Files/deleteIfExists (.resolve root ^String relative)))
      (io/make-parents (.toFile manifest-path))
      (spit (.toFile manifest-path)
            (str (pr-str {:generator generator :kind kind
                          :files (into (sorted-map)
                                       (map (fn [[path source]] [path (digest source)]))
                                       sources)}) "\n"))
      {:generated-dir (str root)
       :namespace-count (count sources)
       :removed-count (count stale)})))

(defn std!
  "Prepare the checked-in std catalog. No Zig invocation or download is needed.
  Use `clojure -X:prepare` in an Aguafria source checkout. Published JARs include
  these entry points, and source consumers use the standard deps prep hook."
  [options]
  (let [catalog (read-edn (or (io/resource "aguafria/zig-std.edn")
                            (throw (ex-info "Missing Zig std catalog" {}))))]
    (write-entrypoints! (assoc options :kind :std :namespaces (:namespaces catalog)))))
