(ns aguafria.generate-keyword
  "Generate Aguafria's Zig token catalog from its embedded Zig and optional ZLS.

  Zig's `std/zig/BuiltinFn.zig` is the completeness authority. ZLS enriches
  those entries with signatures and language-reference documentation."
  (:require [aguafria.zig.toolchain :as toolchain]
            [clojure.data.json :as json]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.set :as set]
            [clojure.string :as str])
  (:import [java.io BufferedInputStream BufferedOutputStream
            ByteArrayOutputStream File]
           [java.math BigInteger]
           [java.nio.charset StandardCharsets]
           [java.nio.file FileVisitOption Files LinkOption Path]
           [java.security MessageDigest]
           [java.util.concurrent TimeUnit]
           [java.lang ProcessBuilder$Redirect]))

(def ^:private catalog-path
  "resources/aguafria/zig-keyword.edn")

(def ^:private std-catalog-path
  "resources/aguafria/zig-std.edn")

(def ^:private std-source-root
  "src/aguafria/std")

(def ^:private std-extractor-path
  "dev/aguafria/extract_std.mjs")

(def ^:private generated-source-header
  ";; Generated by aguafria.generate-keyword. Do not edit.")

(def ^:private reader-token-specs
  [{:name "!"
    :zig-token "!"
    :zig-tag "bang"
    :kind :operator
    :param-count 1
    :documentation "Boolean NOT."}
   {:name "=="
    :zig-token "=="
    :zig-tag "equal_equal"
    :kind :operator
    :minimum-param-count 2
    :documentation "Equality comparison."}
   {:name "!="
    :zig-token "!="
    :zig-tag "bang_equal"
    :kind :operator
    :minimum-param-count 2
    :documentation "Inequality comparison."}
   {:name "<<"
    :zig-token "<<"
    :zig-tag "angle_bracket_angle_bracket_left"
    :kind :operator
    :minimum-param-count 2
    :documentation "Bit shift left."}
   {:name ">>"
    :zig-token ">>"
    :zig-tag "angle_bracket_angle_bracket_right"
    :kind :operator
    :minimum-param-count 2
    :documentation "Bit shift right."}
   {:name "&"
    :zig-token "&"
    :zig-tag "ampersand"
    :kind :operator
    :minimum-param-count 1
    :documentation "Address-of operator."}
   {:name "%" :zig-token "%" :zig-tag "percent"
    :kind :operator :minimum-param-count 2 :documentation "Remainder operator."}
   {:name "|" :zig-token "|" :zig-tag "pipe"
    :kind :operator :minimum-param-count 2 :documentation "Bitwise OR operator."}
   {:name "+%" :zig-token "+%" :zig-tag "plus_percent"
    :kind :operator :minimum-param-count 2 :documentation "Wrapping addition."}
   {:name "-%" :zig-token "-%" :zig-tag "minus_percent"
    :kind :operator :minimum-param-count 2 :documentation "Wrapping subtraction."}
   {:name "*%" :zig-token "*%" :zig-tag "asterisk_percent"
    :kind :operator :minimum-param-count 2 :documentation "Wrapping multiplication."}
   {:name "+|" :zig-token "+|" :zig-tag "plus_pipe"
    :kind :operator :minimum-param-count 2 :documentation "Saturating addition."}
   {:name "-|" :zig-token "-|" :zig-tag "minus_pipe"
    :kind :operator :minimum-param-count 2 :documentation "Saturating subtraction."}
   {:name "*|" :zig-token "*|" :zig-tag "asterisk_pipe"
    :kind :operator :minimum-param-count 2 :documentation "Saturating multiplication."}
   {:name "bit-not"
    :zig-token "~"
    :zig-tag "tilde"
    :kind :operator
    :param-count 1
    :documentation "Bitwise NOT. This Var exists because `~` is reserved by the Clojure reader."}
   {:name "bit-xor"
    :zig-token "^"
    :zig-tag "caret"
    :kind :operator
    :param-count nil
    :minimum-param-count 2
    :documentation "Bitwise XOR. This Var exists because `^` is metadata syntax in the Clojure reader."}
   {:name "div-assign"
    :zig-token "/="
    :zig-tag "slash_equal"
    :kind :assignment
    :param-count 2
    :documentation "Division assignment. This Var exists because `/=` is not a valid Clojure token."}
   {:name "+=" :zig-token "+=" :zig-tag "plus_equal"
    :kind :assignment :param-count 2 :documentation "Addition assignment."}
   {:name "-=" :zig-token "-=" :zig-tag "minus_equal"
    :kind :assignment :param-count 2 :documentation "Subtraction assignment."}
   {:name "*=" :zig-token "*=" :zig-tag "asterisk_equal"
    :kind :assignment :param-count 2 :documentation "Multiplication assignment."}
   {:name "%=" :zig-token "%=" :zig-tag "percent_equal"
    :kind :assignment :param-count 2 :documentation "Remainder assignment."}
   {:name "+%=" :zig-token "+%=" :zig-tag "plus_percent_equal"
    :kind :assignment :param-count 2 :documentation "Wrapping addition assignment."}
   {:name "-%=" :zig-token "-%=" :zig-tag "minus_percent_equal"
    :kind :assignment :param-count 2 :documentation "Wrapping subtraction assignment."}
   {:name "*%=" :zig-token "*%=" :zig-tag "asterisk_percent_equal"
    :kind :assignment :param-count 2 :documentation "Wrapping multiplication assignment."}
   {:name "+|=" :zig-token "+|=" :zig-tag "plus_pipe_equal"
    :kind :assignment :param-count 2 :documentation "Saturating addition assignment."}
   {:name "-|=" :zig-token "-|=" :zig-tag "minus_pipe_equal"
    :kind :assignment :param-count 2 :documentation "Saturating subtraction assignment."}
   {:name "*|=" :zig-token "*|=" :zig-tag "asterisk_pipe_equal"
    :kind :assignment :param-count 2 :documentation "Saturating multiplication assignment."}
   {:name "&=" :zig-token "&=" :zig-tag "ampersand_equal"
    :kind :assignment :param-count 2 :documentation "Bitwise AND assignment."}
   {:name "|=" :zig-token "|=" :zig-tag "pipe_equal"
    :kind :assignment :param-count 2 :documentation "Bitwise OR assignment."}
   {:name "<<=" :zig-token "<<=" :zig-tag "angle_bracket_angle_bracket_left_equal"
    :kind :assignment :param-count 2 :documentation "Left-shift assignment."}
   {:name ">>=" :zig-token ">>=" :zig-tag "angle_bracket_angle_bracket_right_equal"
    :kind :assignment :param-count 2 :documentation "Right-shift assignment."}])

(defn- command-output!
  [command]
  (let [process (-> (ProcessBuilder. ^java.util.List (mapv str command))
                    (.redirectErrorStream true)
                    (.start))
        output (slurp (.getInputStream process))
        exit (.waitFor process)]
    (when-not (zero? exit)
      (throw (ex-info "External command failed while generating Zig keywords"
                      {:command command :exit exit :output output})))
    (str/trim output)))

(defn- sha256-file
  [file]
  (let [digest (MessageDigest/getInstance "SHA-256")
        bytes (Files/readAllBytes (.toPath (io/file file)))]
    (.update digest bytes)
    (format "%064x" (BigInteger. 1 (.digest digest)))))

(defn- regular-files-below
  [root]
  (let [root-path (.toPath (io/file root))
        no-follow (into-array LinkOption [LinkOption/NOFOLLOW_LINKS])]
    (when (Files/isSymbolicLink root-path)
      (throw (ex-info "Refusing to traverse a symbolic-link source root"
                      {:root (str root-path)})))
    (if-not (Files/isDirectory root-path no-follow)
      []
      (with-open [paths (Files/walk root-path (make-array FileVisitOption 0))]
        (->> (iterator-seq (.iterator paths))
             (map (fn [^Path path]
                    (when (Files/isSymbolicLink path)
                      (throw (ex-info "Refusing to traverse a symbolic link"
                                      {:root (str root-path) :path (str path)})))
                    path))
             (filter #(Files/isRegularFile ^Path % no-follow))
             vec)))))

(defn- sha256-tree
  [root extension]
  (let [root-path (.toPath (io/file root))
        files (->> (regular-files-below root)
                   (filter #(str/ends-with? (str %) extension))
                   (sort-by #(str (.relativize root-path ^Path %))))
        digest (MessageDigest/getInstance "SHA-256")]
    (doseq [^Path path files]
      (let [relative (str (.relativize root-path path))]
        (.update digest (.getBytes relative StandardCharsets/UTF_8))
        (.update digest (byte-array [0]))
        (.update digest (Files/readAllBytes path))
        (.update digest (byte-array [0]))))
    {:file-count (count files)
     :sha256 (format "%064x" (BigInteger. 1 (.digest digest)))}))

(defn- zig-environment
  [zig]
  (let [version (command-output! [zig "version"])
        env-output (command-output! [zig "env"])
        lib-dir (second (re-find #"(?m)^\s*\.lib_dir\s*=\s*\"([^\"]+)\"" env-output))]
    (when-not lib-dir
      (throw (ex-info "Could not find .lib_dir in `zig env` output"
                      {:zig zig :output env-output})))
    {:executable zig
     :version version
     :lib-dir lib-dir
     :std-dir (io/file lib-dir "std")
     :std-source (io/file lib-dir "std/std.zig")
     :builtin-source (io/file lib-dir "std/zig/BuiltinFn.zig")
     :tokenizer-source (io/file lib-dir "std/zig/tokenizer.zig")}))

(defn- source-segments
  [source]
  (let [lines (str/split-lines source)
        starts (->> lines
                    (keep-indexed
                     (fn [index line]
                       (when-let [[_ zig-name]
                                  (re-matches #"\s*\"(@[A-Za-z][A-Za-z0-9]*)\",\s*" line)]
                         [index zig-name])))
                    vec)]
    (mapv (fn [position [start zig-name]]
            (let [end (or (first (nth starts (inc position) nil)) (count lines))]
              [zig-name (str/join "\n" (subvec (vec lines) start end))]))
          (range (count starts))
          starts)))

(defn- parse-builtin-segment
  [[zig-name segment]]
  (let [param-text (second (re-find #"\.param_count\s*=\s*(null|[0-9]+)" segment))
        tag-match (re-find #"\.tag\s*=\s*\.(?:@\"([^\"]+)\"|([A-Za-z0-9_]+))" segment)
        eval-match (re-find #"\.eval_to_error\s*=\s*\.([A-Za-z0-9_]+)" segment)]
    (when-not (and param-text tag-match)
      (throw (ex-info "Could not parse a Zig BuiltinFn entry"
                      {:zig-name zig-name :segment segment})))
    (sorted-map
     :allows-lvalue? (boolean (re-find #"\.allows_lvalue\s*=\s*true" segment))
     :eval-to-error (keyword (or (second eval-match) "never"))
     :illegal-outside-function?
     (boolean (re-find #"\.illegal_outside_function\s*=\s*true" segment))
     :name (subs zig-name 1)
     :param-count (when-not (= "null" param-text) (parse-long param-text))
     :tag (or (second tag-match) (nth tag-match 2))
     :zig-name zig-name)))

(defn- parse-builtins
  [file]
  (let [entries (->> (slurp file)
                     source-segments
                     (mapv parse-builtin-segment))
        names (map :zig-name entries)]
    (when (or (< (count entries) 50)
              (not= (count entries) (count (distinct names))))
      (throw (ex-info "The Zig builtin parser produced an implausible catalog"
                      {:file (str file)
                       :count (count entries)
                       :unique-count (count (distinct names))})))
    (vec (sort-by :name entries))))

(defn- parse-keywords
  [file]
  (->> (re-seq #"\.\{\s*\"([A-Za-z][A-Za-z0-9]*)\"\s*,\s*\.keyword_([A-Za-z0-9_]+)\s*\},"
               (slurp file))
       (map (fn [[_ spelling tag]]
              (sorted-map :name spelling :tag tag)))
       distinct
       (sort-by :name)
       vec))

(defn- tokenizer-tags
  [file]
  (->> (re-seq #"(?m)^\s{8}([A-Za-z][A-Za-z0-9_]*),\s*$" (slurp file))
       (map second)
       set))

(defn- read-lsp-line!
  [^BufferedInputStream input]
  (let [output (ByteArrayOutputStream.)]
    (loop []
      (let [byte (.read input)]
        (cond
          (= -1 byte) (throw (ex-info "ZLS closed its output stream" {}))
          (= 10 byte) (-> (.toString output StandardCharsets/UTF_8)
                          (str/replace #"\r$" ""))
          :else (do (.write output byte) (recur)))))))

(defn- read-lsp-message!
  [^BufferedInputStream input]
  (let [headers (loop [headers {}]
                  (let [line (read-lsp-line! input)]
                    (if (str/blank? line)
                      headers
                      (let [[header value] (str/split line #":" 2)]
                        (recur (assoc headers (str/lower-case header)
                                      (str/trim value)))))))
        content-length (some-> (get headers "content-length") parse-long)]
    (when-not content-length
      (throw (ex-info "ZLS response omitted Content-Length" {:headers headers})))
    (let [payload (.readNBytes input (int content-length))]
      (when-not (= content-length (alength payload))
        (throw (ex-info "ZLS response ended before Content-Length bytes"
                        {:expected content-length :actual (alength payload)})))
      (json/read-str (String. payload StandardCharsets/UTF_8) :key-fn keyword))))

(defn- write-lsp-message!
  [^BufferedOutputStream output message]
  (let [payload (.getBytes (json/write-str message) StandardCharsets/UTF_8)
        header (.getBytes (str "Content-Length: " (alength payload) "\r\n\r\n")
                          StandardCharsets/UTF_8)]
    (.write output header)
    (.write output payload)
    (.flush output)))

(defn- await-response!
  [input id]
  (loop []
    (let [message (read-lsp-message! input)]
      (if (= id (:id message)) message (recur)))))

(defn- zls-completions
  [zls]
  (let [process (-> (ProcessBuilder. ^java.util.List [zls "--disable-lsp-logs"])
                    (.redirectError ProcessBuilder$Redirect/INHERIT)
                    (.start))
        input (BufferedInputStream. (.getInputStream process))
        output (BufferedOutputStream. (.getOutputStream process))
        source "const aguafria_catalog = @"
        uri (str (.toURI (io/file ".aguafria-zls-catalog.zig")))]
    (try
      (write-lsp-message!
       output
       {:jsonrpc "2.0" :id 1 :method "initialize"
        :params {:processId nil
                 :rootUri (str (.toURI (io/file ".")))
                 :capabilities
                 {:textDocument
                  {:completion
                   {:completionItem
                    {:documentationFormat ["markdown" "plaintext"]}}}}}})
      (let [initialize (await-response! input 1)]
        (when (:error initialize)
          (throw (ex-info "ZLS initialize failed" {:response initialize}))))
      (write-lsp-message! output {:jsonrpc "2.0" :method "initialized" :params {}})
      (write-lsp-message!
       output
       {:jsonrpc "2.0" :method "textDocument/didOpen"
        :params {:textDocument {:uri uri :languageId "zig" :version 1 :text source}}})
      (write-lsp-message!
       output
       {:jsonrpc "2.0" :id 2 :method "textDocument/completion"
        :params {:textDocument {:uri uri}
                 :position {:line 0 :character (count source)}
                 :context {:triggerKind 2 :triggerCharacter "@"}}})
      (let [response (await-response! input 2)
            result (:result response)
            items (if (map? result) (:items result) result)]
        (when (:error response)
          (throw (ex-info "ZLS builtin completion failed" {:response response})))
        (into {}
              (keep (fn [{:keys [label detail documentation]}]
                      (when (str/starts-with? label "@")
                        [label {:signature detail
                                :documentation
                                (if (map? documentation)
                                  (:value documentation)
                                  documentation)
                                :documentation-format
                                (keyword (or (when (map? documentation)
                                               (:kind documentation))
                                             "plaintext"))}]))
                    items)))
      (finally
        (try
          (write-lsp-message! output
                              {:jsonrpc "2.0" :id 3 :method "shutdown" :params nil})
          (catch Throwable _))
        (.destroy process)
        (.waitFor process 2 TimeUnit/SECONDS)
        (when (.isAlive process) (.destroyForcibly process))))))

(defn- optional-zls-data
  [zls zig-version]
  (try
    (let [zls-version (command-output! [zls "--version"])]
      (if (= zig-version zls-version)
        {:version zls-version :completions (zls-completions zls)}
        (do
          (binding [*out* *err*]
            (println "Skipping ZLS docs: Zig" zig-version "and ZLS" zls-version
                     "do not match."))
          nil)))
    (catch Throwable error
      (binding [*out* *err*]
        (println "Skipping optional ZLS docs:" (ex-message error)))
      nil)))

(defn- fallback-documentation
  [{:keys [zig-name param-count eval-to-error allows-lvalue?
           illegal-outside-function?]}]
  (str "Zig compiler builtin `" zig-name "`. The compiler table declares "
       (if (some? param-count)
         (str param-count " parameter" (when (not= 1 param-count) "s"))
         "a variable parameter count")
       ", error evaluation `" (name eval-to-error) "`"
       (when allows-lvalue? ", and permits use as an lvalue")
       (when illegal-outside-function? ", and restricts it to function scope")
       "."))

(defn generate-catalog
  "Return a fresh catalog derived from Zig and, when available, matching ZLS."
  [{:keys [zls] :or {zls (or (System/getenv "AGUAFRIA_ZLS") "zls")}
    :as options}]
  (when (contains? options :zig)
    (throw (ex-info "Aguafria's Zig compiler is embedded and cannot be configured"
                    {:aguafria/phase :embedded-zig-configuration
                     :value (:zig options)})))
  (let [zig (toolchain/executable)
        {:keys [version builtin-source tokenizer-source] :as zig-env}
        (zig-environment zig)
        _ (doseq [^File file [builtin-source tokenizer-source]]
            (when-not (.isFile file)
              (throw (ex-info "The installed Zig source file was not found"
                              {:file (str file) :zig zig-env}))))
        builtins (parse-builtins builtin-source)
        keywords (parse-keywords tokenizer-source)
        token-tags (tokenizer-tags tokenizer-source)
        reader-tokens
        (mapv (fn [{:keys [zig-tag] :as token}]
                (when-not (contains? token-tags zig-tag)
                  (throw (ex-info "Aguafria reader token disappeared from Zig's tokenizer"
                                  {:tag zig-tag :source (str tokenizer-source)})))
                (into (sorted-map) token))
              reader-token-specs)
        zls-data (optional-zls-data zls version)
        completions (:completions zls-data)
        builtins (mapv (fn [builtin]
                         (let [completion (get completions (:zig-name builtin))]
                           (into (sorted-map)
                                 (merge builtin
                                        {:documentation
                                         (or (:documentation completion)
                                             (fallback-documentation builtin))
                                         :documentation-format
                                         (or (:documentation-format completion) :markdown)
                                         :documentation-source
                                         (if completion :zls-langref :zig-compiler-table)
                                         :signature
                                         (or (:signature completion)
                                             (str (:zig-name builtin) "(...)"))}))))
                       builtins)
        compiler-names (set (map :zig-name builtins))
        zls-names (set (keys completions))]
    (when (and (seq completions) (not= compiler-names zls-names))
      (binding [*out* *err*]
        (println "ZLS enrichment differs from Zig's authoritative builtin table:"
                 {:missing-in-zls (sort (set/difference compiler-names zls-names))
                  :extra-in-zls (sort (set/difference zls-names compiler-names))})))
    (sorted-map
     :builtins builtins
     :generated-by "aguafria.generate-keyword"
     :keywords keywords
     :reader-tokens reader-tokens
     :schema-version 1
     :sources
     (sorted-map
      :builtin-table
      (sorted-map :path "std/zig/BuiltinFn.zig"
                  :sha256 (sha256-file builtin-source))
      :language-reference
      (when zls-data
        (sorted-map
         :extra-builtins (vec (sort (set/difference zls-names compiler-names)))
         :missing-builtins (vec (sort (set/difference compiler-names zls-names)))
         :provider :zls
         :version (:version zls-data)))
      :tokenizer
      (sorted-map :path "std/zig/tokenizer.zig"
                  :sha256 (sha256-file tokenizer-source)))
     :zig-version version)))

(defn- quoted-zig-name
  [name]
  (if (and (str/starts-with? name "@\"") (str/ends-with? name "\""))
    (json/read-str (subs name 1))
    name))

(defn- clojure-var-name
  [zig-name]
  (let [name (quoted-zig-name zig-name)
        name (str/replace name
                          #"[^A-Za-z0-9*+!_?<>=.$%&-]"
                          (fn [match]
                            (str "-u" (format "%04x" (int (first match))) "-")))
        name (if (contains? #{"nil" "true" "false"} name)
               (str name "-value")
               name)
        name (if (re-find #"^[A-Za-z*+!_?<>=.$%&-]" name)
               name
               (str "zig-" name))]
    (if (or (str/blank? name) (#{"." ".."} name))
      (str "zig-name-" (subs (sha256-file (io/file std-extractor-path)) 0 8))
      name)))

(defn- namespace-path-replacements
  [namespaces]
  (->> namespaces
       (group-by #(str/lower-case (str/join "." (:path %))))
       (mapcat
        (fn [[_ entries]]
          (when (< 1 (count entries))
            (let [paths (mapv :path entries)
                  winner (or (some (fn [path]
                                     (when (= (peek path)
                                              (str/lower-case (peek path)))
                                       path))
                                   paths)
                             (first (sort-by #(str/join "." %) paths)))]
              (for [path paths :when (not= path winner)]
                [path (str (peek path) "_Zig")])))))
       (into {})))

(defn- clojure-namespace-path
  [path replacements]
  (mapv (fn [index segment]
          (get replacements (subvec path 0 (inc index)) segment))
        (range (count path))
        path))

(defn- std-namespace-name
  [path replacements]
  (let [path (clojure-namespace-path path replacements)]
  (symbol (str "aguafria.std"
               (when (seq path) (str "." (str/join "." path)))))))

(defn- ensure-unique-clojure-names
  [namespace-name members]
  (let [members (mapv #(assoc % :clojure-name (clojure-var-name (:name %))) members)
        duplicates (->> members
                        (group-by :clojure-name)
                        (keep (fn [[name entries]]
                                (when (< 1 (count entries))
                                  [name (mapv :name entries)])))
                        (into (sorted-map)))]
    (when (seq duplicates)
      (throw (ex-info "Zig std declarations collide as Clojure Var names"
                      {:namespace namespace-name :collisions duplicates})))
    members))

(defn- dedupe-analyzed-std-members
  [namespace-name members]
  (->> members
       (group-by :name)
       (map (fn [[name entries]]
              (let [zig-names (distinct (map :zig-name entries))]
                (when-not (= 1 (count zig-names))
                  (throw (ex-info "Zig std analysis returned conflicting declarations"
                                  {:namespace namespace-name
                                   :name name
                                   :zig-names zig-names})))
                (apply max-key #(count (or (:documentation %) "")) entries))))
       (sort-by :name)
       vec))

(defn- normalize-std-namespace
  [zig-version replacements namespace]
  (let [namespace-name (std-namespace-name (:path namespace) replacements)
        members (->> (dedupe-analyzed-std-members namespace-name
                                                  (:members namespace))
                     (mapv (fn [member]
                             (-> member
                                 (update :category keyword)
                                 (assoc :zig-version zig-version))))
                     (ensure-unique-clojure-names namespace-name)
                     (mapv (fn [member]
                             (assoc member :symbol
                                    (symbol (str namespace-name)
                                            (:clojure-name member))))))]
    (-> namespace
        (assoc :name namespace-name :members members :zig-path (:path namespace))
        (dissoc :path))))

(defn- generate-zig-docs!
  [{:keys [executable std-source version]}]
  (let [docs-root (io/file ".aguafria/generator"
                           (str "zig-docs-" (str/replace version #"[^A-Za-z0-9_.-]" "_")))
        docs-dir (io/file docs-root "docs")]
    (.mkdirs docs-root)
    (command-output!
     [executable "build-lib" (.getAbsolutePath ^File std-source)
      "-fno-emit-bin" (str "-femit-docs=" (.getAbsolutePath docs-dir))])
    (doseq [file [(io/file docs-dir "main.wasm")
                  (io/file docs-dir "sources.tar")]]
      (when-not (.isFile ^File file)
        (throw (ex-info "Zig documentation generation omitted a required artifact"
                        {:file (str file) :docs-dir (str docs-dir)}))))
    docs-dir))

(defn generate-std-catalog
  "Return the complete public Zig std namespace/declaration graph. Zig's own
  documentation semantic walker is the authority, including resolved aliases,
  nested containers, signatures, documentation, and source locations."
  [{:keys [node]
    :or {node (or (System/getenv "AGUAFRIA_NODE") "node")}
    :as options}]
  (when (contains? options :zig)
    (throw (ex-info "Aguafria's Zig compiler is embedded and cannot be configured"
                    {:aguafria/phase :embedded-zig-configuration
                     :value (:zig options)})))
  (let [zig (toolchain/executable)
        {:keys [version std-dir std-source] :as zig-env} (zig-environment zig)
        extractor (io/file std-extractor-path)]
    (doseq [^File file [std-source extractor]]
      (when-not (.isFile file)
        (throw (ex-info "A Zig std generator input is missing"
                        {:file (str file)}))))
    (let [docs-dir (generate-zig-docs! zig-env)
          extracted (-> (command-output!
                         [node (.getAbsolutePath extractor)
                          (.getAbsolutePath (io/file docs-dir "main.wasm"))
                          (.getAbsolutePath (io/file docs-dir "sources.tar"))])
                        (json/read-str :key-fn keyword))
          replacements (namespace-path-replacements (:namespaces extracted))
          namespaces (mapv (partial normalize-std-namespace version replacements)
                           (:namespaces extracted))
          member-count (reduce + (map (comp count :members) namespaces))
          tree-hash (sha256-tree std-dir ".zig")]
      (when (or (< (count namespaces) 100)
                (< member-count 1000)
                (not= (count namespaces) (count (distinct (map :name namespaces)))))
        (throw (ex-info "Zig's std documentation graph produced an implausible catalog"
                        {:namespace-count (count namespaces)
                         :member-count member-count})))
      (sorted-map
       :generated-by "aguafria.generate-keyword"
       :member-count member-count
       :namespaces namespaces
       :schema-version 1
       :sources
       (sorted-map
        :extractor (sorted-map :path std-extractor-path
                               :sha256 (sha256-file extractor))
        :std (merge (sorted-map :path "std/std.zig"
                                :provider :zig-documentation-wasm)
                    tree-hash))
       :wasm-diagnostic-count (:diagnostic-count extracted)
       :zig-version version))))

(defn- existing-generated-std-files
  []
  (let [root (io/file std-source-root)
        root-path (.toPath root)]
    (->> (regular-files-below root)
         (filter #(str/ends-with? (str %) ".clj"))
         (map #(str (.relativize (.toPath (.getAbsoluteFile (io/file ".")))
                                 (.toAbsolutePath ^Path %))))
         set)))

(defn- delete-generated-std-files!
  []
  (let [stale (sort (existing-generated-std-files))
        generated-root (.normalize (.toAbsolutePath (.toPath (io/file std-source-root))))]
    (doseq [path stale]
      (let [file (io/file path)
            resolved (.normalize (.toAbsolutePath (.toPath file)))
            first-line (when (.isFile file)
                         (first (str/split-lines (slurp file))))]
        (when-not (and (.startsWith resolved generated-root)
                       (= generated-source-header first-line)
                       (not (Files/isSymbolicLink resolved)))
          (throw (ex-info "Refusing to delete a non-generated std namespace"
                          {:path path :resolved (str resolved)})))
        (Files/delete resolved)))
    stale))

(defn- std-output-current?
  [rendered-catalog]
  (and (= rendered-catalog
          (when (.isFile (io/file std-catalog-path))
            (slurp std-catalog-path)))
       (empty? (existing-generated-std-files))))

(defn- write-std-output!
  [rendered-catalog namespace-count]
  (let [deleted (delete-generated-std-files!)]
    (io/make-parents (io/file std-catalog-path))
    (spit std-catalog-path rendered-catalog)
    {:deleted-count (count deleted)
     :namespace-count namespace-count}))

(defn- render-catalog
  [catalog]
  (binding [*print-length* nil
            *print-level* nil]
    (with-out-str (pprint/pprint catalog))))

(defn- compiler-derived-shape
  "Remove optional ZLS enrichment so `--check` also works without ZLS."
  [catalog]
  (-> catalog
      (update :builtins
              #(mapv (fn [builtin]
                       (dissoc builtin :documentation :documentation-format
                               :documentation-source :signature))
                     %))
      (update :sources dissoc :language-reference)))

(defn -main
  [& args]
  (let [check? (some #{"--check"} args)
        unknown (remove #{"--check"} args)]
    (when (seq unknown)
      (throw (ex-info "Unknown keyword generator options"
                      {:unknown unknown :supported ["--check"]})))
    (let [catalog (generate-catalog {})
          std-catalog (generate-std-catalog {})
          rendered (render-catalog catalog)
          rendered-std (render-catalog std-catalog)
          output (io/file catalog-path)
          existing (when (.isFile output) (slurp output))
          existing-catalog (when (and check? existing) (edn/read-string existing))
          keyword-current? (when check?
                             (if (get-in catalog [:sources :language-reference])
                               (= existing rendered)
                               (= (compiler-derived-shape existing-catalog)
                                  (compiler-derived-shape catalog))))
          std-current? (when check? (std-output-current? rendered-std))]
      (if check?
        (if (and keyword-current? std-current?)
          (do
            (println "Zig keyword catalog is current:" catalog-path)
            (println "Zig std EDN catalog is current:"
                     std-catalog-path))
          (do
            (binding [*out* *err*]
              (when-not keyword-current?
                (println "Zig keyword catalog is stale:" catalog-path))
              (when-not std-current?
                (println "Zig std catalog is stale or generated namespace shims remain:"
                         std-catalog-path))
              (println "Run: clojure -M:generate-keyword"))
            (System/exit 1)))
        (do
          (io/make-parents output)
          (spit output rendered)
          (let [{:keys [deleted-count namespace-count]}
                (write-std-output! rendered-std (count (:namespaces std-catalog)))]
            (println "Generated" catalog-path "with"
                     (count (:builtins catalog)) "Zig builtins.")
            (println "Generated" std-catalog-path "with"
                     (:member-count std-catalog) "public std declarations across"
                     namespace-count "EDN-derived Clojure namespaces; removed"
                     deleted-count "obsolete generated namespace files.")))))))
