(ns racing-game.physical-race-test
  "World-owning integration fixtures: run in the test process, not a live race."
  (:require [aguafria.std]
            [aguafria.keyword :as ak]
            [aguafria.std.mem :as mem]
            [aguafria.zig :as az]
            [racing-game.simulation :as sim]
            [racing-game.race-status :as status]
            [racing-game.worker :as worker]
            [racing-game.protocol :as protocol]
            [racing-game.physics :as physics]
            [racing-game.vehicle-driver :as driver]
            [racing-game.vehicle-recovery :as recovery]
            [racing-game.vehicle-turnaround :as turnaround]
            [aguafria-examples-native.bindings.box3d :as b3]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.test :refer [deftest is]]))

(az/defn pit-state-tread-probe
  "QA-owned race world. Measured tire work is generated by physical driving;
  only pit-state labels are fixtures. This is not an AI/pit navigation test."
  :- [:array 4 :f32] []
  (sim/configure-countdown! 0)
  (sim/reset!)
  (ak/defer (sim/shutdown!))
  (let [car (az/deref (sim/vehicle-pointer 0))
        racer (sim/racer-pointer 0)
        ^:var losses (mem/zeroes (az/type [:array 4 :f32]))]
    (dotimes [_ physics/step-rate]
      (physics/drive! car 0.0 1.0 0.0)
      (physics/step! sim/dynamics-world))
    (set! _ (physics/take-vehicle-tread-loss! car))
    (dotimes [state 4]
      (set! (az/field racer pit_state) (ak/intCast state))
      (set! (az/field racer tire_condition) 1.0)
      (dotimes [_ physics/step-rate]
        (physics/drive! car 1.0 0.0 0.0)
        (physics/step! sim/dynamics-world))
      (sim/update-tire-strategy! 0)
      (set! (az/index losses state) (- 1.0 (az/field racer tire_condition))))
    losses))

(deftest pit-call-does-not-disable-tire-wear-test
  (let [[track called servicing exiting :as loss] (az/value (pit-state-tread-probe))]
    (prn :pit-state-tread-loss {:track track :called called :servicing servicing :exiting exiting})
    (is (pos? track) (pr-str loss))
    (is (pos? called) "Calling the pits does not freeze tread condition")
    (is (zero? servicing) "Work is consumed without charging the tires being serviced")
    (is (pos? exiting) "Fresh tires accrue work during pit exit")))

(az/defstruct LanguageControlResult {:layout :extern}
  [[:hold_reason :u8] [:follow_reason :u8] [:stale_reason :u8] [:expired_reason :u8]
   [:install_displacement :f32] [:held_throttle :f32] [:held_brake :f32]
   [:distance :f32] [:ticks :u64] [:revision :u64]
   [:fixture_not_llm :bool] [:reply_preserved :bool] [:rejected_preserves_plan :bool]
   [:expiry_throttle :f32] [:expiry_brake :f32]])

(az/defn fixture-language-plan!
  "Explicit manual fixture submission. Never attribute these words to AI."
  :- :u8 [[index :usize] [revision :u64] [expires :u64] [text [:slice-const :u8]]]
  (sim/install-language-plan! index sim/race-epoch revision sim/simulation-tick expires
    (az/field text ptr) (az/field text len) true false))

(az/defn language-control-probe
  "World-owning integration: only pedals move bodies; no inference or fake
  model result is used in this deterministic safety/controller fixture."
  :- LanguageControlResult []
  (sim/configure-countdown! 0)
  (sim/reset!)
  (ak/defer (sim/shutdown!))
  (set! _ (sim/set-items-enabled! false))
  (dotimes [i sim/racer-count] (set! _ (sim/enable-language-driving! i true)))
  (dotimes [i sim/team-count]
    (set! (az/field (az/deref (sim/team-pointer i)) next_decision_tick) 1000000000))
  (let [before (sim/vehicle-pose 0 0)
        hold-text "Plan: hold\nRadio: I am waiting for the track to clear."
        hold-reason (fixture-language-plan! 0 1 1200 hold-text)
        after (sim/vehicle-pose 0 0)
        event (sim/language-event-at 1)
        ^:var result (mem/zeroes (az/type LanguageControlResult))]
    (set! (az/field result hold_reason) hold-reason)
    (set! (az/field result install_displacement)
      (+ (ak/abs (- (az/field after x) (az/field before x)))
         (ak/abs (- (az/field after y) (az/field before y)))
         (ak/abs (- (az/field after z) (az/field before z)))))
    (set! (az/field result fixture_not_llm) (ak/! (az/field event generated)))
    (set! (az/field result reply_preserved)
      (mem/eql (az/type :u8)
        (az/slice (az/field event text) 0 (az/field event byte_count)) hold-text))
    ;; Simulate a recovery trying to drive: the production final gate must win.
    (set! (az/field (az/index sim/vehicle-controls 0) throttle) 1.0)
    (set! (az/field (az/index sim/vehicle-controls 0) brake) 0.0)
    (sim/enforce-language-holds!)
    (set! (az/field result held_throttle) (az/field (az/index sim/vehicle-controls 0) throttle))
    (set! (az/field result held_brake) (az/field (az/index sim/vehicle-controls 0) brake))
    (dotimes [i sim/racer-count]
      (let [reason (fixture-language-plan! i 2 1200 "Plan: follow\nRadio: Continuing at a safe pace.")]
        (when (ak/== i 0) (set! (az/field result follow_reason) reason))))
    (sim/step-many! 120)
    (let [moved (sim/vehicle-pose 0 0)
          dx (- (az/field moved x) (az/field after x))
          dy (- (az/field moved y) (az/field after y))]
      (set! (az/field result distance) (ak/sqrt (+ (* dx dx) (* dy dy)))))
    (set! (az/field result stale_reason)
      (fixture-language-plan! 0 2 1200 "Plan: hold\nRadio: This reply is old."))
    (set! (az/field result expired_reason)
      (fixture-language-plan! 0 3 120 "Plan: hold\nRadio: This reply is expired."))
    (set! (az/field result rejected_preserves_plan)
      (ak/== (az/field (az/index sim/language-drivers 0) kind) protocol/plan-follow))
    (set! (az/field result revision) (az/field (az/index sim/language-drivers 0) revision))
    (set! (az/field result ticks) sim/simulation-tick)
    ;; Expiry of the installed plan is a pedal gate, not a stopped clock.
    (set! (az/field (az/index sim/language-drivers 0) expires_tick) sim/simulation-tick)
    (sim/enforce-language-holds!)
    (set! (az/field result expiry_throttle) (az/field (az/index sim/vehicle-controls 0) throttle))
    (set! (az/field result expiry_brake) (az/field (az/index sim/vehicle-controls 0) brake))
    result))

(deftest readable-plans-control-real-pedals-without-teleporting-test
  (worker/stop!)
  (let [result (az/value (language-control-probe))]
    (is (= 0 (:hold_reason result) (:follow_reason result)) (pr-str result))
    (is (= 0.0 (:install_displacement result)))
    (is (= 0.0 (:held_throttle result) (:expiry_throttle result)))
    (is (= 1.0 (:held_brake result) (:expiry_brake result)))
    (is (> (:distance result) 0.1) (pr-str result))
    (is (= 120 (:ticks result)))
    (is (= 2 (:revision result)))
    (is (= 4 (:stale_reason result)))
    (is (= 5 (:expired_reason result)))
    (is (:fixture_not_llm result))
    (is (:reply_preserved result))
    (is (:rejected_preserves_plan result))
    (println :readable-plan-physical-result result)))

(az/defn captured-grid-recovery-controls-probe
  "Recreate the measured forty-body pile-up as fixture INITIAL CONDITIONS.
  Run the real Flecs recovery integration once; no integration step teleports,
  adds progress, reclassifies drivers, or attributes fixed test intents to AI."
  :- [:array 2 driver/Control]
  [[poses [:array 8 [:array 5 physics/BodyState]]]
   [controls [:array 8 driver/Control]] [state recovery/State]]
  (sim/configure-countdown! 0)
  (sim/reset!)
  (ak/defer (sim/shutdown!))
  (dotimes [i 8]
    (let [car (az/deref (sim/vehicle-pointer i))
          racer (sim/racer-pointer i)
          control (az/index controls i)]
      (dotimes [part 5]
        (let [body (if (ak/== part 0) (az/field car chassis)
                     (az/index (az/field car wheels) (- part 1)))
              pose (az/index (az/index poses i) part)]
          (b3/b3Body_SetTransform body
            (b3/b3Pos {:x (az/field pose x) :y (az/field pose y) :z (az/field pose z)})
            (b3/b3Quat {:v {:x (az/field pose qx) :y (az/field pose qy) :z (az/field pose qz)}
                         :s (az/field pose qw)}))))
      (set! (az/field (az/deref racer) progress) (az/field control progress))
      (set! (az/field (az/deref racer) lane) (/ (az/field control lane) 50.0))
      (set! (az/field (az/deref racer) speed) (* (az/field control speed) 0.001))
      (set! (az/field (az/deref racer) heading)
        ;; Measured orientation, not the road tangent.
        (turnaround/heading (az/index (az/index poses i) 0)))))
  ;; This historical capture has eight cars. Keep that fixture unchanged while
  ;; the live simulation's storage contains the complete twenty-driver field.
  (dotimes [i 8]
    (set! (az/index sim/vehicle-controls i) (az/index controls i)))
  (set! (az/field (az/deref (sim/recovery-pointer 0)) state) state)
  (set! (az/field (az/deref (sim/brain-pointer 0)) lane_target) 0.075)
  (sim/update-recovery! sim/vehicle-controls)
  (az/array-init [:array 2 driver/Control]
    [(az/index sim/vehicle-controls 0) (az/field (sim/recovery-view 0) control)]))

(deftest captured-pileup-veto-is-used-by-the-simulation-test
  (worker/stop!)
  (let [racers (:racers (edn/read-string
                         (slurp (io/resource "fixtures/blocked-grid-2026-09-08.edn"))))
        controls (mapv #(get-in % [:recovery :control]) racers)
        [result observed] (az/value
                 (captured-grid-recovery-controls-probe
                   (mapv :poses racers) controls
                   (recovery/State (get-in racers [0 :recovery :state]))))]
    (is (pos? (:throttle (first controls))))
    (is (zero? (:throttle result)) "The actual recovery integration must use the veto")
    (is (= 1.0 (:brake result)))
    (is (= result observed) "Inspection and physics must report the same final pedals")
    (is (= (:steering (az/value (driver/Control (first controls)))) (:steering result)))))

(az/defstruct RacePhysicsResult {:layout :extern}
  [[:minimum_speed :f32] [:minimum_up :f32] [:maximum_pose_error :f32]
   [:stable_component :bool] [:ticks :u64]])

(az/defn controlled-grid-probe
  "Exercise the real simulation loop with explicit test intents, not LLM output."
  :- RacePhysicsResult []
  (sim/configure-countdown! 0)
  (sim/reset!)
  (set! _ (sim/set-items-enabled! false))
  (dotimes [i sim/racer-count]
    (let [brain (sim/brain-pointer i)]
      (set! (az/field (az/deref brain) next_decision_tick) 1000000000)
      (set! (az/field (az/deref brain) target_speed) 0.035)))
  (dotimes [i sim/team-count]
    (set! (az/field (az/deref (sim/team-pointer i)) next_decision_tick) 1000000000))
  (let [address (ak/intFromPtr (sim/vehicle-pointer 0))
        ^{:var :f32} speed 1000.0
        ^{:var :f32} up 1.0
        ^{:var :f32} pose-error 0.0]
    (sim/step-many! 1200)
    (dotimes [i sim/racer-count]
      (let [view (sim/racer-view (ak/intCast i)) state (sim/vehicle-pose i 0)]
        (set! speed (ak/min speed (* 1000.0 (az/field view speed))))
        (set! up (ak/min up (- 1.0 (* 2.0 (+ (* (az/field state qx) (az/field state qx))
                                           (* (az/field state qy) (az/field state qy)))))))
        (set! pose-error (ak/max pose-error
          (+ (ak/abs (- (* 1000.0 (az/field view x)) (az/field state x)))
             (ak/abs (- (* 1000.0 (az/field view y)) (az/field state y))))))))
    (RacePhysicsResult {:minimum_speed speed :minimum_up up :maximum_pose_error pose-error
                         :stable_component (ak/== address (ak/intFromPtr (sim/vehicle-pointer 0)))
                         :ticks (az/field (sim/snapshot) tick)})))

(deftest flecs-race-is-driven-by-rigid-bodies-test
  (worker/stop!)
  (let [result (az/value (controlled-grid-probe))]
    (is (> (:minimum_speed result) 5.0) (pr-str result))
    (is (> (:minimum_up result) 0.8) (pr-str result))
    (is (< (:maximum_pose_error result) 0.001) (pr-str result))
    (is (:stable_component result) (pr-str result))
    (is (= 1200 (:ticks result)) (pr-str result))))

(az/defstruct ClassificationResult {:layout :extern}
  [[:ended :bool] [:finishers :u8] [:retired :u8] [:rank_a :u8] [:rank_b :u8]
   [:dnf_finished :bool] [:dnf_laps :u16] [:frozen_progress :f32]
   [:restart_clean :bool]])

(az/defn classification-probe
  "Explicit classification fixture, not a claim of an eight-AI complete race."
  :- ClassificationResult []
  (sim/configure-countdown! 0)
  (sim/reset!)
  (ak/defer (sim/shutdown!))
  (dotimes [i sim/racer-count]
    (let [racer (sim/racer-pointer i) brain (sim/brain-pointer i)]
      (set! (az/field (az/deref brain) next_decision_tick) 1000000000)
      (set! (az/field (az/deref racer) finished) (< i 6))
      (set! (az/field (az/deref racer) lap) (if (< i 6) 3 (if (ak/== i 6) 1 0)))
      (set! (az/field (az/deref racer) finish_tick) (if (< i 6) (+ 100 i) 0))
      (when (>= i 6)
        (set! (az/deref (sim/status-pointer i))
              (status/Entry {:retired true :reason status/reason-overturned
                             :invalid_ticks 600 :retired_tick 99
                             :lap (az/field (az/deref racer) lap) :progress 0.4})))))
  (sim/step!)
  ;; A wreck moved by later contact must not acquire classification distance.
  (set! (az/field (az/deref (sim/racer-pointer 7)) progress) 0.99)
  (sim/update-ranks!)
  (let [snapshot (sim/snapshot)
        ^:var result (ClassificationResult
                      {:ended (ak/== (az/field snapshot state) sim/race-state-finished)
                       :finishers (az/field snapshot finished) :retired (sim/retired-count)
                       :rank_a (az/field (sim/racer-view 6) rank)
                       :rank_b (az/field (sim/racer-view 7) rank)
                       :dnf_finished (az/field (sim/racer-view 6) finished)
                       :dnf_laps (az/field (sim/racer-view 6) lap)
                       :frozen_progress (sim/classification-progress 7)
                       :restart_clean false})]
    (sim/shutdown!)
    (set! _ (sim/initialize!))
    (set! (az/field result restart_clean)
          (and (ak/== (sim/retired-count) 0)
               (ak/!= (ak/intFromPtr (sim/status-pointer 0)) 0)
               (ak/!= (ak/intFromPtr (sim/recovery-pointer 0)) 0)
               (ak/== (az/field (az/field (sim/recovery-view 0) state) phase) 0)
               (ak/== (az/field (az/field (sim/recovery-view 0) state) waiting_ticks) 0)
               (> (az/field (sim/vehicle-pose 0 0) qw) -2.0)))
    result))

(deftest dnf-classification-is-not-a-finish-test
  (worker/stop!)
  (let [result (az/value (classification-probe))]
    (is (:ended result))
    (is (= 6 (:finishers result)))
    (is (= (- (az/value sim/racer-count) 6) (:retired result)))
    (is (= [7 8] [(:rank_a result) (:rank_b result)]))
    (is (false? (:dnf_finished result)))
    (is (= 1 (:dnf_laps result)))
    (is (< (abs (- 0.4 (:frozen_progress result))) 1.0e-5))
    (is (:restart_clean result))))

(az/defn retired-team-prompt-probe :- worker/PromptBuffer []
  (let [^:var request (mem/zeroes (az/type worker/InferenceRequest))]
    (set! (az/field request team) 3)
    (set! (az/field request driver_a) 6)
    (set! (az/field request driver_b) 7)
    (set! (az/field request rank_a) 8)
    (set! (az/field request rank_b) 8)
    (set! (az/field request tire_a) 100)
    (set! (az/field request tire_b) 100)
    (set! (az/field request damage_a) 100)
    (set! (az/field request damage_b) 100)
    (set! (az/field request pit_a) 4)
    (set! (az/field request pit_b) 4)
    (set! (az/field request box_occupied) true)
    (worker/team-prompt request)))

(deftest retired-team-observation-is-readable-and-bounded-test
  (let [{:keys [byte_count bytes]} (az/value (retired-team-prompt-probe))
        prompt (String. (byte-array (map unchecked-byte (take byte_count bytes)))
                        java.nio.charset.StandardCharsets/UTF_8)]
    (is (< 0 byte_count 160) prompt)
    (is (= 2 (count (re-seq #"retired" prompt))) prompt)
    (is (re-find #"A6:.*B7:" prompt) prompt)))

(az/defn finished-car-clearance-probe
  "An explicit early-finisher fixture must keep physically moving while the
  remaining cars race. No body transforms or fake finish crossings."
  :- [:array 3 :f32] []
  (sim/configure-countdown! 0)
  (sim/reset!)
  (ak/defer (sim/shutdown!))
  (dotimes [i sim/racer-count]
    (let [brain (sim/brain-pointer i)]
      (set! (az/field (az/deref brain) next_decision_tick) 1000000000)
      (set! (az/field (az/deref brain) target_speed) 0.035)))
  (dotimes [i sim/team-count]
    (set! (az/field (az/deref (sim/team-pointer i)) next_decision_tick) 1000000000))
  (let [racer (sim/racer-pointer 0)]
    (set! (az/field (az/deref racer) finished) true)
    (set! (az/field (az/deref racer) finish_tick) 1234)
    (sim/step-many! 360)
    (az/array-init [:array 3 :f32]
      [(* 1000.0 (az/field (sim/racer-view 0) speed))
       (ak/as :f32 (ak/floatFromInt (az/field (sim/racer-view 0) finish_tick)))
       (ak/as :f32 (ak/floatFromInt (az/field (sim/snapshot) state)))])))

(deftest finishers-clear-the-line-under-wheel-power-test
  (worker/stop!)
  (let [[speed finish-tick state] (az/value (finished-car-clearance-probe))]
    (is (> speed 10.0))
    (is (= 1234.0 finish-tick))
    (is (= 1.0 state))))

(az/defn lapped-wreck-observation-probe
  "Explicit sensor fixture: classification must not hide physical obstacles."
  :- :u8 []
  (sim/configure-countdown! 0)
  (sim/reset!)
  (ak/defer (sim/shutdown!))
  (dotimes [i sim/racer-count]
    (let [racer (sim/racer-pointer i)]
      (set! (az/field (az/deref racer) progress) (* 0.1 (ak/as :f32 (ak/floatFromInt i))))
      (set! (az/field (az/deref racer) lane) 0.0)
      (set! (az/field (az/deref racer) speed) 0.0)
      (set! (az/field (az/deref racer) stun_seconds) 0.0)
      (set! (az/field (az/deref racer) shielded) false)))
  (let [self (sim/racer-pointer 0) wreck (sim/racer-pointer 1)
        ^{:var :u8} checks 0]
    (set! (az/field (az/deref self) progress) 0.999)
    (set! (az/field (az/deref self) lap) 2)
    (set! (az/field (az/deref wreck) progress) 0.001)
    (set! (az/field (az/deref (sim/status-pointer 1)) retired) true)
    (when (ak/== (sim/choose-target 0) 1) (set! checks (+ checks 1)))
    (when (ak/== (sim/target-distance-bin 0 1) 0) (set! checks (+ checks 2)))
    (when (ak/== (sim/racer-tactical-status 0) sim/tactical-status-hazard)
      (set! checks (+ checks 4)))
    ;; A stationary car outside our corridor is visible but not blocking it.
    (set! (az/field (az/deref wreck) lane) 0.2)
    (when (ak/== (sim/racer-tactical-status 0) sim/tactical-status-clear)
      (set! checks (+ checks 8)))
    checks))

(deftest graphics-loading-preserves-the-physics-link-test
  ;; physics/physics-track may be loaded before the simulation's graphics
  ;; bindings in a fresh runner. All later native trampolines still need Box3D.
  (is (some #(re-find #"aguafria_box3d" (str %))
            (:zig-args (az/configuration)))
      "Loading shared graphics must retain the optional Box3D link input"))

(deftest future-pit-calls-do-not-disable-main-circuit-clearance-test
  (doseq [[state progress expected] [[0 0.9 false] [1 0.66 false]
                                    [1 0.8499 false] [1 0.85 true]
                                    [1 0.97 true] [1 0.99 false]
                                    [2 0.97 true] [3 0.02 true]]]
    (is (= expected (sim/pit-navigation-active? state progress 0.969))
        (pr-str {:state state :progress progress}))))

(deftest tactical-status-does-not-hide-hazards-behind-shields-test
  ;; Pure native classification: safe to evaluate in an existing live world.
  (doseq [stunned [false true]
          hazard [false true]
          shielded [false true]]
    (is (= (cond stunned 2 hazard 1 shielded 3 :else 0)
           (sim/classify-tactical-status stunned hazard shielded))
        (pr-str {:stunned stunned :hazard hazard :shielded shielded}))))

(deftest lapped-wrecks-remain-visible-to-the-model-test
  (worker/stop!)
  (let [checks (lapped-wreck-observation-probe)]
    (is (= 15 checks)
        (pr-str {:target-visible (bit-test checks 0)
                 :wrapped-distance (bit-test checks 1)
                 :hazard-visible (bit-test checks 2)
                 :outside-corridor-clear (bit-test checks 3)}))))
